baseURL = "https://brunolevi.dev/"
languageCode = "es-mx"
theme = "MainTheme"
title = "Bruno Levi Dev"
defaultContentLanguage = "es"
googleAnalytics = 'UA-144643471-1'

[params]
  description = "Soy del Estado de Morelos, México y me especializo en el desarrollo de software, especificamente en las áreas de telemetría, IoT, etc."
  images = ["https://s3.us-east-2.amazonaws.com/brunovelazquez.com.bucket/bg-about.webp"]
  title = "Bruno Levi Dev"
[taxonomies]
  tags = "tags"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    noHl = false
    style = "dracula"
    tabWidth = 4

[menu]
  [[menu.main]]
    name = "Home"
    pre = ""
    url = "/"
    weight = 1
  [[menu.social]]
    name = "Github"
    pre = "github"
    url = "https://github.com/levidotpy"
    weight = 1
  [[menu.social]]
    name = "Instagram"
    pre = "instagram"
    url = "https://www.instagram.com/brunolevidev"
    weight = 2
  [[menu.social]]
    name = "Twitter"
    pre = "twitter"
    url = "https://twitter.com/brunolevidev"
    weight = 3
  [[menu.social]]
    name = "Email"
    pre = "mail"
    url = "mailto:contacto.bruno.velazquez@gmail.com"
    weight = 4
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'