baseURL = "https://brunovelazquez.com/"
languageCode = "es-mx"
theme = "cactus"
title = "Bruno Velázquez"

[params]
colortheme = "white"
description = "Ingeniero en desarrollo de software, entusiasta de IoT y Videojuegos"
copyright = "Bruno Velázquez"
googleAnalytics = "UA-144643471-1"
mainSectionTitle = "Posts recientes"
images = ["https://s3.us-east-2.amazonaws.com/brunovelazquez.com.bucket/bg-index.webp"]
rss = true
tagsOverview = true # show tags overview by default.
showProjectsList = true # show projects list by default (if projects data file exists).
projectsUrl = "https://github.com/brunovelazquez" # title link for projects list

[params.comments]
enabled = false

[[params.social]]
name = "github"
link = "https://github.com/brunovelazquez"

[[params.social]]
name = "email"
link = "contacto.bruno.velazquez@gmail.com" # no need for "mailto:" at the start

[[params.social]]
name = "instagram"
link = "https://www.instagram.com/brunovelazquez_/"

[[params.social]]
name = "twitter"
link = "https://twitter.com/brunovelazquez_/"

[[menu.main]]
name = "Inicio"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "Acerca"
url = "/acerca"
weight = 4

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4
