baseURL = "https://brunovelazquez.com/"
languageCode = "es-mx"
theme = "MainTheme"
title = "Bruno Velázquez"
defaultContentLanguage = "es"

[params]
  description = "Soy del Estado de Morelos, México y me especializo en desarrollar soluciones integrales para tu negocio o empresa"
  images = ["https://s3.us-east-2.amazonaws.com/brunovelazquez.com.bucket/bg-about.webp"]
  title = "Bruno Velázquez"
[taxonomies]
  tags = "tags"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    noHl = false
    style = "dracula"
    tabWidth = 4

[menu]
  [[menu.main]]
    name = "Home"
    pre = ""
    url = "/"
    weight = 1
  [[menu.social]]
    name = "Github"
    pre = "github"
    url = "https://github.com/BrunoVelazquez"
    weight = 1
  [[menu.social]]
    name = "Instagram"
    pre = "instagram"
    url = "https://www.instagram.com/brunovelazquez_/"
    weight = 2
  [[menu.social]]
    name = "Twitter"
    pre = "twitter"
    url = "https://twitter.com/brunovelazquez_"
    weight = 3
  [[menu.social]]
    name = "Email"
    pre = "mail"
    url = "mailto:contacto@brunovelazquez.com"
    weight = 4