baseURL = "https://brunovelazquez.com/"
languageCode = "es-mx"
theme = "MainTheme"
title = "Bruno Velázquez"

[menu]
  [[menu.main]]
    name = "Home"
    pre = ""
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    pre = ""
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    pre = ""
    url = "/tags/"
    weight = 3
  [[menu.social]]
    name = "Github"
    pre = "github"
    url = "https://github.com/BrunoVelazquez"
    weight = 1
  [[menu.social]]
    name = "Instagram"
    pre = "instagram"
    url = "https://www.instagram.com/brunovelazquez_/"
    weight = 2
  [[menu.social]]
    name = "Twitter"
    pre = "twitter"
    url = "https://twitter.com/brunovelazquez_"
    weight = 3